import { BatchAnalyzeResponse, FarmContext, SilageTelemetryResponse, DigitalTwinLedgerResponse } from "./api";

export const fallbackFarmContext: FarmContext = {
  farm_profile: {
    farm_name: "Shiv Dairy Farm",
    location: "Pune Region, Maharashtra",
    lactating_animals: 17,
    dry_animals: 7,
    daily_milk_yield_liters: 260,
    ration_group: "lactating",
    lactation_stage: "early_lactation",
    data_source: "DEMO REFERENCE — Field Tested Profile",
  },
  feed_basket: [
    { name: "Maize Silage", quantity_kg: 20, cp_pct: 8.8, dm_pct: 34.5, data_source: "NIR Chemometrics Sensor" },
    { name: "Green Fodder", quantity_kg: 10, cp_pct: 11.2, dm_pct: 22.0, data_source: "Field Scan" },
    { name: "Dry Fodder", quantity_kg: 4, cp_pct: 4.2, dm_pct: 88.5, data_source: "Reference Database" },
    { name: "Concentrate", quantity_kg: 5, cp_pct: 18.5, dm_pct: 90.0, data_source: "Lab Verified" },
    { name: "Cottonseed Meal", quantity_kg: 1.5, cp_pct: 36.0, dm_pct: 90.0, data_source: "Supplier Label" },
    { name: "Mineral Mixture", quantity_kg: 0.2, cp_pct: 0.0, dm_pct: 98.0, data_source: "ICAR Standard" },
  ],
  updated_at: new Date().toISOString(),
};

export function getFallbackBatchData(feedType: string = "Maize Silage", scenario: string = "healthy"): BatchAnalyzeResponse {
  const wavelengths = Array.from({ length: 51 }, (_, i) => 800 + i * 5);
  const baseCurve = wavelengths.map((wl) => 0.25 + 0.15 * Math.sin((wl - 800) / 50) + 0.05 * Math.cos((wl - 850) / 30));
  
  const points = ["P1 (Top-Left)", "P2 (Top-Right)", "P3 (Center)", "P4 (Bottom-Left)", "P5 (Bottom-Right)"].map((label, idx) => ({
    point_id: `PT-0${idx + 1}`,
    reflectance: baseCurve.map((val) => Number((val + (idx * 0.01) - 0.02).toFixed(4))),
  }));

  const now = new Date();
  const timeSeries = Array.from({ length: 48 }, (_, i) => {
    const d = new Date(now.getTime() - (47 - i) * 3600000);
    const coreTemp = 24.5 + Math.sin(i / 6) * 1.8;
    const ambTemp = 22.0 + Math.sin(i / 6 - 0.5) * 4.0;
    return {
      hour_offset: -(47 - i),
      timestamp: d.toISOString(),
      core_temp_c: Number(coreTemp.toFixed(1)),
      ambient_temp_c: Number(ambTemp.toFixed(1)),
      temp_delta_c: Number((coreTemp - ambTemp).toFixed(1)),
      ph: Number((3.85 + Math.sin(i / 10) * 0.08).toFixed(2)),
      humidity_pct: 68.5,
      moisture_pct: 65.2,
      feed_mass_kg: 1240,
      dT_dt: 0.02,
      cumulative_heat_units: 14.2,
      status: "OPTIMAL",
    };
  });

  return {
    batch_id: `FS-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}-DEMO`,
    feed_type: feedType,
    scenario: scenario,
    nir_data: {
      wavelengths,
      points,
      scenario,
    },
    cv_screening: {
      visual_anomaly_detected: scenario === "adulteration",
      anomaly_score: scenario === "adulteration" ? 0.78 : 0.08,
      mould_risk_level: scenario === "storage_warning" ? "HIGH_RISK" : "LOW",
      mould_coverage_pct: scenario === "storage_warning" ? 14.5 : 0.2,
      foreign_material_detected: scenario === "adulteration",
      texture_uniformity: 0.92,
      color_consistency_score: 0.88,
      screening_summary: scenario === "healthy" 
        ? "Visual inspection confirms clean, well-fermented olive-green silage with uniform chop length and zero mould spotting."
        : "Automated screening flag detected. Verify physical characteristics with laboratory inspection.",
    },
    storage_telemetry: {
      ph: scenario === "storage_warning" ? 5.2 : 3.88,
      temperature_celsius: scenario === "storage_warning" ? 38.5 : 24.2,
      ambient_temp_c: 22.4,
      temp_differential_c: 1.8,
      humidity_pct: 68.5,
      moisture_pct: 65.5,
      feed_mass_kg: 1240,
      exposure_days: 7.0,
      spoilage_risk_index: scenario === "storage_warning" ? 78 : 12,
      status: scenario === "storage_warning" ? "SPOILAGE_WARNING" : "STABLE_FERMENTED",
      status_color: scenario === "storage_warning" ? "rose" : "emerald",
      status_label: scenario === "storage_warning" ? "Elevated Temperature Alert" : "Well-Preserved (Lactic Dominated)",
      telemetry_badge: "LONGITUDINAL TELEMETRY SYNCHRONIZED",
      dT_dt: 0.02,
      max_dT_dt: 0.15,
      delta_t_24h: 0.4,
      aerobic_heating_detected: scenario === "storage_warning",
      cumulative_heat_units: 14.2,
      shelf_life_hours_remaining: 336,
      advisory_message: "Silage core temperature and lactic acid levels are within optimum anaerobic fermentation boundaries.",
      recommended_action: "Maintain current silo compaction and feed face management.",
      recent_time_series: timeSeries,
      flieg_evaluation: {
        flieg_score: 88,
        grade: "VERY_GOOD",
        grade_label: "Very Good Fermentation (Class I)",
        badge_color: "emerald",
        description: "Excellent lactic acid preservation with negligible butyric acid synthesis.",
        ph_evaluated: 3.88,
        dry_matter_pct: 34.5,
        acid_profile: {
          lactic_acid_pct: 6.2,
          acetic_acid_pct: 1.8,
          butyric_acid_pct: 0.08,
          lactic_to_acetic_ratio: 3.44,
          ideal_ratio_benchmark: "3:1 to 4:1 (Lactic dominant)",
        },
      },
    },
    nutritional_analysis: {
      dry_matter_pct: 34.5,
      moisture_pct: 65.5,
      crude_protein_pct: 8.8,
      ndf_pct: 44.2,
      adf_pct: 26.8,
      is_simulated_data: true,
      data_badge: "PLSR HYBRID MODEL (ISO 12099)",
      mahalanobis_distance: scenario === "ood" ? 3.45 : 1.12,
      is_ood: scenario === "ood",
      domain_status: scenario === "ood" ? "OUT_OF_DISTRIBUTION" : "IN_DOMAIN_CALIBRATED",
      calibration_fit_pct: 96.4,
      uncertainty_sigma: {
        dry_matter: 0.45,
        crude_protein: 0.22,
        ndf: 0.85,
        adf: 0.62,
      },
      confidence_intervals: {
        dry_matter: [33.6, 35.4],
        crude_protein: [8.4, 9.2],
        ndf: [42.5, 45.9],
        adf: [25.6, 28.0],
      },
      sand_silica_screening: {
        estimated_aia_pct: 1.8,
        baseline_tilt_delta_r: 0.012,
        baseline_mean_r: 0.28,
        risk_level: "LOW_CLEAN",
        risk_label: "Low Sand & Silica Contamination",
        badge_color: "EMERALD",
        advisory: "Spectra shows minimal soil grit or silica contamination (< 2.5% AIA safe threshold).",
      },
      mineral_balance: {
        estimated_ca_pct: 0.42,
        estimated_p_pct: 0.28,
        ca_to_p_ratio: 1.5,
        status: "OPTIMAL",
        status_label: "Ideal Ca:P Ratio (1.5:1)",
        badge_color: "EMERALD",
        ideal_range: "1.4:1 to 2.0:1",
        advisory: "Macro-mineral balance supports optimum milk synthesis and skeletal bone homeostasis.",
      },
    },
    evidence: {
      evidence_score: 94,
      evidence_level: "HIGH_CONFIDENCE",
      trust_status: "TRUSTED",
      metrics: {
        spectral_quality: 96,
        sample_consistency: 92,
        calibration_fit: 95,
        prediction_uncertainty: 91,
        visual_agreement: 94,
        ood_distance: 98,
      },
      untrusted_reasons: [],
      recommendation: "Batch meets all quality and nutritional benchmarks. Approved for immediate dairy herd feeding.",
    },
    dairy_ration: {
      herd_summary: {
        lactating_animals: 17,
        dry_animals: 7,
        total_herd: 24,
      },
      ration_analysis: {
        tested_feed_cp_pct: 8.8,
        basket_weighted_cp_pct: 14.8,
        target_cp_pct: 15.0,
        cp_gap_pct: -0.2,
        cp_status: "BALANCED",
        fiber_status: "OPTIMAL",
        basis: "Dry Matter Intake (DMI)",
        stage_name: "Early Lactation (Peak Yield)",
        required_dm_total_kg: 289.0,
        required_dmi_per_animal_kg: 17.0,
        available_dm_total_kg: 295.4,
      },
      dairy_interpretation: "Ration provides 14.8% CP on DM basis against 15.0% requirement. Effective fiber (eNDF) is within target to prevent subacute ruminal acidosis (SARA).",
    },
    ration_optimizer: {
      status: "OPTIMAL_FEASIBLE",
      solver: "SciPy HiGHS LP Solver",
      herd_context: {
        lactation_stage: "early_lactation",
        animal_count: 17,
        daily_milk_yield_liters: 260,
        target_dmi_kg: 17.0,
        target_cp_pct: 15.0,
        target_cp_kg: 2.55,
        target_ndf_min_pct: 28.0,
        target_ndf_max_pct: 36.0,
      },
      cost_summary: {
        current_cost_per_cow_day_inr: 248.5,
        optimal_cost_per_cow_day_inr: 218.0,
        daily_saving_per_cow_inr: 30.5,
        daily_herd_saving_inr: 518.5,
        monthly_herd_saving_inr: 15555.0,
        savings_pct: 12.3,
      },
      nutrition_balance: {
        current_dmi_kg: 17.2,
        optimal_dmi_kg: 17.0,
        current_cp_pct: 14.8,
        optimal_cp_pct: 15.2,
        optimal_cp_kg: 2.58,
        current_ndf_pct: 32.4,
        optimal_ndf_pct: 31.8,
        forage_to_concentrate_ratio: "62:38",
        rumen_acidosis_risk: "LOW_SAFE",
      },
      allocation_table: [
        { name: "Maize Silage", price_per_kg_inr: 3.5, optimal_as_fed_kg: 22.0, optimal_dm_kg: 7.59, optimal_daily_cost_inr: 77.0, current_as_fed_kg: 20.0, current_daily_cost_inr: 70.0, pct_of_dmi: 44.6, is_forage: true, cp_pct: 8.8, dm_pct: 34.5, ndf_pct: 44.2 },
        { name: "Green Fodder", price_per_kg_inr: 2.2, optimal_as_fed_kg: 12.0, optimal_dm_kg: 2.64, optimal_daily_cost_inr: 26.4, current_as_fed_kg: 10.0, current_daily_cost_inr: 22.0, pct_of_dmi: 15.5, is_forage: true, cp_pct: 11.2, dm_pct: 22.0, ndf_pct: 52.0 },
        { name: "Dry Fodder", price_per_kg_inr: 4.8, optimal_as_fed_kg: 2.5, optimal_dm_kg: 2.21, optimal_daily_cost_inr: 12.0, current_as_fed_kg: 4.0, current_daily_cost_inr: 19.2, pct_of_dmi: 13.0, is_forage: true, cp_pct: 4.2, dm_pct: 88.5, ndf_pct: 68.0 },
        { name: "Concentrate Feed", price_per_kg_inr: 22.0, optimal_as_fed_kg: 4.2, optimal_dm_kg: 3.78, optimal_daily_cost_inr: 92.4, current_as_fed_kg: 5.0, current_daily_cost_inr: 110.0, pct_of_dmi: 22.2, is_forage: false, cp_pct: 18.5, dm_pct: 90.0, ndf_pct: 22.0 },
        { name: "Cottonseed Meal", price_per_kg_inr: 32.0, optimal_as_fed_kg: 0.8, optimal_dm_kg: 0.72, optimal_daily_cost_inr: 25.6, current_as_fed_kg: 1.5, current_daily_cost_inr: 48.0, pct_of_dmi: 4.2, is_forage: false, cp_pct: 36.0, dm_pct: 90.0, ndf_pct: 30.0 },
        { name: "Mineral Mixture", price_per_kg_inr: 75.0, optimal_as_fed_kg: 0.2, optimal_dm_kg: 0.20, optimal_daily_cost_inr: 15.0, current_as_fed_kg: 0.2, current_daily_cost_inr: 15.0, pct_of_dmi: 1.2, is_forage: false, cp_pct: 0.0, dm_pct: 98.0, ndf_pct: 0.0 },
      ],
      advisory: "Least-cost ration reduces concentrate overfeeding while sustaining peak milk yield, saving ~₹15,555/month across the lactating herd.",
    },
    advisories: [
      {
        id: "ADV-01",
        severity: "OPTIMAL",
        category: "NUTRITION",
        title: "Fermentation Quality Verified",
        message: "Silage dry matter (34.5%) and pH (3.88) indicate optimal anaerobic fermentation.",
        verification_required: false,
      },
      {
        id: "ADV-02",
        severity: "INFO",
        category: "RATION",
        title: "Ration Cost Optimization Potential",
        message: "Adjusting dry fodder and concentrate proportion can yield ₹518/day herd savings.",
        verification_required: false,
      },
    ],
    digital_twin: {
      batch_id: `FS-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}-DEMO`,
      feed_type: feedType,
      scenario: scenario,
      current_state: "FIELD_VERIFIED",
      integrity_hash: "0x8f4d92a1c7e5b304918e62d47cfb0832ea51d9e2a47890bc1f2e4681a95c3b17",
      created_at: now.toISOString(),
      timeline: [
        { step: "1", title: "Batch Ingestion & Sample Logged", timestamp: now.toISOString(), status: "COMPLETED", detail: "5-point W-pattern NIR scan executed." },
        { step: "2", title: "Chemometrics PLSR Inference", timestamp: now.toISOString(), status: "COMPLETED", detail: "Dry matter, CP, NDF, and ADF predicted with 96% fit." },
        { step: "3", title: "Flieg Fermentation Score", timestamp: now.toISOString(), status: "COMPLETED", detail: "Score 88/100 (Very Good Preservation)." },
        { step: "4", title: "Cryptographic Block Sealed", timestamp: now.toISOString(), status: "COMPLETED", detail: "SHA-256 genesis hash generated and verified." },
      ],
      passport: {
        title: "FeedSure 360 Digital Feed Passport",
        passport_id: "PASS-2026-FS-99182",
        issued_at: now.toISOString(),
        device_node: "NIR-SpectroNode-V4 #082",
        model_version: "FeedSure Chemometrics v2026.5",
        current_lifecycle_state: "FEEDING_APPROVED",
        genesis_hash: "0x1a89c42b...f802",
        chain_tip_hash: "0x8f4d92a1...3b17",
        total_lifecycle_blocks: 4,
        standards_compliance: ["ISO 12099:2017", "ASTM E1655", "ICAR/NRC 2021"],
        verification_status: "CRYPTOGRAPHICALLY_VERIFIED",
        verification_badge: "SEALED IMMUTABLE RECORD",
      },
    },
    farm_profile: fallbackFarmContext.farm_profile,
    feed_basket: fallbackFarmContext.feed_basket,
    data_provenance: {
      mode: "STANDALONE_DEMO_HYBRID",
      measurement_source: "NIR Diffuse Reflectance 5-Point Scan (800nm - 1050nm)",
      sampling_source: "ISO 12099 Dynamic 5-Point W/X Spatial Grid",
      nutrition_source: "Chemometrics PLSR Multi-Target Model (ISO 12099 / ASTM E1655)",
      vision_source: "Computer Vision Texture & Spoilage Screening",
      evidence_source: "Multi-Source Evidence Fusion (NIR Consistency, Calibration Fit)",
      storage_source: "Multi-Sensor Storage Telemetry (pH, Temp, Moisture)",
      record_created_at: now.toISOString(),
    },
  };
}

export function getFallbackSilageTelemetry(batchId: string): SilageTelemetryResponse {
  const data = getFallbackBatchData();
  return {
    batch_id: batchId,
    total_readings: 48,
    summary: data.storage_telemetry,
    time_series: data.storage_telemetry.recent_time_series || [],
    telemetry_badge: "DEMO SIMULATION SERIES",
  };
}

export function getFallbackLedger(batchId: string): DigitalTwinLedgerResponse {
  return {
    batch_id: batchId,
    verification: {
      is_valid: true,
      total_blocks: 4,
      genesis_hash: "0x1a89c42b890f1234567890abcdef1234567890abcdef1234567890abcdef12",
      latest_block_hash: "0x8f4d92a1c7e5b304918e62d47cfb0832ea51d9e2a47890bc1f2e4681a95c3b17",
      chain_algorithm: "SHA-256 (Canonical Payload Hashing)",
      verified_at: new Date().toISOString(),
    },
    events: [
      {
        event_id: "EVT-01",
        batch_id: batchId,
        block_index: 0,
        timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
        state: "INGESTED",
        action: "SAMPLE_REGISTRATION",
        actor: "OPERATOR",
        payload: { feed_type: "Maize Silage", source: "Silo Pit #2" },
        previous_hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        block_hash: "0x1a89c42b890f1234567890abcdef1234567890abcdef1234567890abcdef12",
        detail: "Batch registered and assigned tracking ID.",
      },
      {
        event_id: "EVT-02",
        batch_id: batchId,
        block_index: 1,
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        state: "SCANNED",
        action: "NIR_SPECTROSCOPY",
        actor: "CHEMOMETRICS_ENGINE",
        payload: { dry_matter: 34.5, crude_protein: 8.8, fit_score: 0.96 },
        previous_hash: "0x1a89c42b890f1234567890abcdef1234567890abcdef1234567890abcdef12",
        block_hash: "0x4b7c29e1f8901234567890abcdef1234567890abcdef1234567890abcdef34",
        detail: "5-point spectral scan completed with in-domain calibration.",
      },
      {
        event_id: "EVT-03",
        batch_id: batchId,
        block_index: 2,
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        state: "TELEMETRY_SYNCED",
        action: "IOT_STORAGE_POLL",
        actor: "TELEMETRY_NODE",
        payload: { core_temp: 24.2, ph: 3.88, flieg_grade: "VERY_GOOD" },
        previous_hash: "0x4b7c29e1f8901234567890abcdef1234567890abcdef1234567890abcdef34",
        block_hash: "0x6d9f01a3b8901234567890abcdef1234567890abcdef1234567890abcdef56",
        detail: "Silage fermentation parameters confirmed stable.",
      },
      {
        event_id: "EVT-04",
        batch_id: batchId,
        block_index: 3,
        timestamp: new Date().toISOString(),
        state: "FIELD_VERIFIED",
        action: "RATION_ALLOCATION",
        actor: "DAIRY_NUTRITIONIST",
        payload: { recommendation: "APPROVED_FOR_FEEDING", target_herd: "Lactating Herd" },
        previous_hash: "0x6d9f01a3b8901234567890abcdef1234567890abcdef1234567890abcdef56",
        block_hash: "0x8f4d92a1c7e5b304918e62d47cfb0832ea51d9e2a47890bc1f2e4681a95c3b17",
        detail: "Ration formulated and sealed on ledger.",
      },
    ],
    available_states: ["INGESTED", "SCANNED", "TELEMETRY_SYNCED", "FIELD_VERIFIED", "DISPATCHED", "CONSUMED"],
  };
}
